# Generated by Django 5.2.1 on 2025-05-16 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_menu_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.zona'),
        ),
    ]
