# Generated by Django 5.2.1 on 2025-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='id_reserva',
            field=models.CharField(default='RESERVA000001', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
