# Generated by Django 5.2.1 on 2025-05-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_id_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada')], default='borrador', max_length=20),
        ),
    ]
