# Generated by Django 5.2.1 on 2025-05-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comensales',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
