# Generated by Django 5.2.1 on 2025-05-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('reservas', '0006_reserva_comensales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
