# Generated by Django 5.2 on 2025-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cliente'), (2, 'Mesero'), (3, 'Cocinero'), (4, 'Administrador')], default=1),
        ),
    ]
