# Generated by Django 5.2.1 on 2025-05-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_customuser_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='foto_perfil',
        ),
    ]
