# Generated by Django 5.2.1 on 2025-05-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_remove_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
