# Generated by Django 5.2.1 on 2025-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
